version: '3.3'
services:
  decadevs_docker_adedotun:
    container_name: decadevs-docker-oladipupo
    image: decadevs-docker-oladipupo
    build: ./
    ports:
      - "8532:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3340:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oladipupo
      MYSQL_USER: oladipupo
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: oladipupo